services:
  - type: web
    name: bybit-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
      - key: BYBIT_API_KEY
        sync: false
      - key: BYBIT_API_SECRET
        sync: false
      # Uncomment these if your code uses Telegram too:
      # - key: TELEGRAM_BOT_TOKEN
      #   sync: false
      # - key: TELEGRAM_CHAT_ID
      #   sync: false
